### PR TITLE
Serve, unit test and e2e tests

### PR DESCRIPTION
**Pull request by dimkk**
Download template from Ionic Market
npm install download node packages
bower install will download bower packages (ionic is depending on 1.4.3 of angular and mock is on 1.4.7 which leads to conflict, so manual install)
gulp initialize download tsd dependencies
gulp to compile once*
ionic serve or cordova build 'platform', in order to get nice reload experience with serve you should create ionic-project file in app folder - you can take ionic-project-sample to start
gulp test for one test run of unit-tests in tests folder, gulp test:auto for continious runs (in develop)
gulp protractor for e2e tests from e2e folder in ionic and gulp protractor:ripple for ripple - in develop

### CODE REVIEW

**Comment by CKGrafico** [comment]
I like it a lot!! but I'm not sure if is it ready to be on master, let me check and maybe we can do some changes and improvements.

thanks :D

PS: You cand add yourself into readme on contributors list

**Comment by dimkk** [comment]
Ok, I'll be in touch. Can you reccommend me, what to improve to make a good PR?

**Comment by CKGrafico** [comment]
Check that the variables that are you using have the same convetion name than the others of the project ***(var plugins = require('gulp-load-plugins')(); => var $ = require('gulp-load-plugins')();)*** we can discuss if is better to use $ instead of plugins but we have to write the same.

Be sure that if something is not finished has the enought value to be on the pull request or you can create a branch with this feature and work on it before create the request, etc..***( `gulp test` for one test run of unit-tests in tests folder, `gulp test:auto` for continious runs (in develop))***

**Comment by dimkk** [comment]
Ok, I will consider this, thank you.

**Comment by CKGrafico** [comment]
I think It's OK, two more thinks before accept,
remove IDs on tags use classes and if are only for tests I think that's better to don't put things that you don't use in your logic only for tests no?
I have to take some minutes testing all of this (soon I expect!)

**Comment by CKGrafico** [comment]
It is totally imposible to don't need to do that?
```- `bower install` *will download bower packages* (ionic is depending on 1.4.3 of angular and mock is on 1.4.7 which leads to conflict, so manual install) ```
(yes I'm checking your pull request xD)

**Comment by dimkk** [comment]
1. I will try to find the solution
2. Well, ok - this test is for illustration how to perform e2e test. I use ids because its unique identifiers of objects, which was my target, still I consider your opinion.
3. Seems like protractor still needs to be finished. I will remove it with next commit.

Thanks for your time!

**Comment by CKGrafico** [comment]
Thank you for tour contrinution :)

**Comment by CKGrafico** [comment]
Hey @dimkk if you want I can create a featrue branch for that, accepto your pull to this new branch and work on it at the same time.

**Comment by dimkk** [comment]
That would be nice, thank you - still no progress with main-bower-files. Override dependencie doesn't work. Considering 2 options:
1) Work out this override issue and submit pull request
2) A bit of gulp initialize task refactor

**Comment by CKGrafico** [comment]
there is https://github.com/CKGrafico/Cordova-Multiplatform-Template/tree/feature/Serve%2C_unit_test_and_e2e_tests

**Comment by CKGrafico** [comment]
there is https://github.com/CKGrafico/Cordova-Multiplatform-Template/tree/feature/Serve%2C_unit_test_and_e2e_tests @dimkk

**Comment by CKGrafico** [comment]
@dimkk you're on readme ;) https://github.com/CKGrafico/Cordova-Multiplatform-Template you can make a pull request to the specific branch that I've created if you want.

**Pull request closed without merging**
